import type { Subject } from "../types";

export const anglaisCm1: Subject = {
  id: "anglais-cm1",
  name: "Anglais",
  icon: "🇬🇧",
  colorFrom: "from-violet-500",
  colorTo: "to-purple-600",
  chapters: [
    {
      id: "colors-numbers",
      title: "Colors & Numbers",
      description: "Les couleurs et les nombres jusqu'à 20",
      icon: "🎨",
      exercises: [
        { id: "en-cn-q01", type: "qcm", prompt: "Comment dit-on « rouge » en anglais ?", options: ["red", "blue", "green", "black"], correctIndex: 0 },
        { id: "en-cn-q02", type: "qcm", prompt: "Comment dit-on « bleu » en anglais ?", options: ["blue", "yellow", "white", "brown"], correctIndex: 0 },
        { id: "en-cn-q03", type: "fill-blank", prompt: "Traduis « jaune » en anglais : ___", acceptedAnswers: ["yellow"] },
        { id: "en-cn-q04", type: "qcm", prompt: "Comment dit-on « sept » en anglais ?", options: ["seven", "six", "eight", "seventeen"], correctIndex: 0 },
        { id: "en-cn-q05", type: "qcm", prompt: "« Twelve » signifie :", options: ["douze", "deux", "vingt", "dix"], correctIndex: 0 },
        { id: "en-cn-q06", type: "true-false", prompt: "« Green » signifie « vert ».", correct: true },
        { id: "en-cn-q07", type: "fill-blank", prompt: "Traduis « quinze » en anglais : ___", acceptedAnswers: ["fifteen"] },
        { id: "en-cn-q08", type: "qcm", prompt: "Comment dit-on « noir » en anglais ?", options: ["black", "white", "pink", "purple"], correctIndex: 0 },
        { id: "en-cn-q09", type: "qcm", prompt: "« Twenty » signifie :", options: ["vingt", "deux", "douze", "dix"], correctIndex: 0 },
        { id: "en-cn-q10", type: "true-false", prompt: "« Orange » se dit pareil en français et en anglais.", correct: true },
      ],
    },
    {
      id: "animals",
      title: "Animals",
      description: "Le nom des animaux en anglais",
      icon: "🐶",
      exercises: [
        { id: "en-an-q01", type: "qcm", prompt: "Comment dit-on « chien » en anglais ?", options: ["dog", "cat", "bird", "fish"], correctIndex: 0 },
        { id: "en-an-q02", type: "qcm", prompt: "Comment dit-on « chat » en anglais ?", options: ["cat", "dog", "cow", "duck"], correctIndex: 0 },
        { id: "en-an-q03", type: "fill-blank", prompt: "Traduis « oiseau » en anglais : ___", acceptedAnswers: ["bird"] },
        { id: "en-an-q04", type: "qcm", prompt: "« Horse » signifie :", options: ["cheval", "vache", "mouton", "cochon"], correctIndex: 0 },
        { id: "en-an-q05", type: "qcm", prompt: "Comment dit-on « lapin » en anglais ?", options: ["rabbit", "rat", "rooster", "raccoon"], correctIndex: 0 },
        { id: "en-an-q06", type: "true-false", prompt: "« Fish » signifie « poisson ».", correct: true },
        { id: "en-an-q07", type: "fill-blank", prompt: "Traduis « vache » en anglais : ___", acceptedAnswers: ["cow"] },
        { id: "en-an-q08", type: "qcm", prompt: "« Mouse » signifie :", options: ["souris", "moustique", "mouche", "ours"], correctIndex: 0 },
        { id: "en-an-q09", type: "qcm", prompt: "Comment dit-on « mouton » en anglais ?", options: ["sheep", "ship", "shop", "shoe"], correctIndex: 0 },
        { id: "en-an-q10", type: "true-false", prompt: "« Duck » signifie « canard ».", correct: true },
      ],
    },
    {
      id: "family",
      title: "Family",
      description: "Les membres de la famille",
      icon: "👨‍👩‍👧",
      exercises: [
        { id: "en-fa-q01", type: "qcm", prompt: "Comment dit-on « maman » en anglais ?", options: ["mum", "dad", "sister", "brother"], correctIndex: 0 },
        { id: "en-fa-q02", type: "qcm", prompt: "Comment dit-on « papa » en anglais ?", options: ["dad", "mum", "aunt", "uncle"], correctIndex: 0 },
        { id: "en-fa-q03", type: "fill-blank", prompt: "Traduis « frère » en anglais : ___", acceptedAnswers: ["brother"] },
        { id: "en-fa-q04", type: "qcm", prompt: "« Sister » signifie :", options: ["sœur", "frère", "cousine", "tante"], correctIndex: 0 },
        { id: "en-fa-q05", type: "qcm", prompt: "Comment dit-on « grand-père » en anglais ?", options: ["grandfather", "grandmother", "father", "uncle"], correctIndex: 0 },
        { id: "en-fa-q06", type: "true-false", prompt: "« Grandmother » signifie « grand-mère ».", correct: true },
        { id: "en-fa-q07", type: "fill-blank", prompt: "Traduis « oncle » en anglais : ___", acceptedAnswers: ["uncle"] },
        { id: "en-fa-q08", type: "qcm", prompt: "« Aunt » signifie :", options: ["tante", "oncle", "cousin", "nièce"], correctIndex: 0 },
        { id: "en-fa-q09", type: "qcm", prompt: "Comment dit-on « les parents » en anglais ?", options: ["parents", "family", "children", "kids"], correctIndex: 0 },
      ],
    },
    {
      id: "body-clothes",
      title: "Body & Clothes",
      description: "Les parties du corps et les vêtements",
      icon: "👕",
      exercises: [
        { id: "en-bc-q01", type: "qcm", prompt: "Comment dit-on « tête » en anglais ?", options: ["head", "hand", "foot", "eye"], correctIndex: 0 },
        { id: "en-bc-q02", type: "qcm", prompt: "Comment dit-on « main » en anglais ?", options: ["hand", "head", "hair", "ear"], correctIndex: 0 },
        { id: "en-bc-q03", type: "fill-blank", prompt: "Traduis « pied » en anglais : ___", acceptedAnswers: ["foot"] },
        { id: "en-bc-q04", type: "qcm", prompt: "« Eyes » signifie :", options: ["yeux", "oreilles", "mains", "pieds"], correctIndex: 0 },
        { id: "en-bc-q05", type: "qcm", prompt: "Comment dit-on « chaussures » en anglais ?", options: ["shoes", "shirt", "shorts", "hat"], correctIndex: 0 },
        { id: "en-bc-q06", type: "true-false", prompt: "« T-shirt » se dit presque pareil en français et en anglais.", correct: true },
        { id: "en-bc-q07", type: "fill-blank", prompt: "Traduis « pantalon » en anglais : ___", acceptedAnswers: ["trousers", "pants"] },
        { id: "en-bc-q08", type: "qcm", prompt: "« Hat » signifie :", options: ["chapeau", "veste", "robe", "ceinture"], correctIndex: 0 },
        { id: "en-bc-q09", type: "qcm", prompt: "Comment dit-on « chaussettes » en anglais ?", options: ["socks", "shoes", "shorts", "scarf"], correctIndex: 0 },
      ],
    },
    {
      id: "food",
      title: "Food",
      description: "Les aliments et les repas",
      icon: "🍎",
      exercises: [
        { id: "en-fo-q01", type: "qcm", prompt: "Comment dit-on « pomme » en anglais ?", options: ["apple", "banana", "bread", "milk"], correctIndex: 0 },
        { id: "en-fo-q02", type: "qcm", prompt: "Comment dit-on « pain » en anglais ?", options: ["bread", "butter", "cheese", "cake"], correctIndex: 0 },
        { id: "en-fo-q03", type: "fill-blank", prompt: "Traduis « lait » en anglais : ___", acceptedAnswers: ["milk"] },
        { id: "en-fo-q04", type: "qcm", prompt: "« Cheese » signifie :", options: ["fromage", "beurre", "œuf", "sucre"], correctIndex: 0 },
        { id: "en-fo-q05", type: "qcm", prompt: "Comment dit-on « eau » en anglais ?", options: ["water", "juice", "tea", "soup"], correctIndex: 0 },
        { id: "en-fo-q06", type: "true-false", prompt: "« Chocolate » signifie « chocolat ».", correct: true },
        { id: "en-fo-q07", type: "fill-blank", prompt: "Traduis « banane » en anglais : ___", acceptedAnswers: ["banana"] },
        { id: "en-fo-q08", type: "qcm", prompt: "« Egg » signifie :", options: ["œuf", "lait", "fromage", "pain"], correctIndex: 0 },
        { id: "en-fo-q09", type: "qcm", prompt: "Comment dit-on « petit-déjeuner » en anglais ?", options: ["breakfast", "lunch", "dinner", "snack"], correctIndex: 0 },
      ],
    },
    {
      id: "days-months",
      title: "Days, months & weather",
      description: "Les jours, les mois et le temps qu'il fait",
      icon: "📅",
      exercises: [
        { id: "en-dm-q01", type: "qcm", prompt: "Comment dit-on « lundi » en anglais ?", options: ["Monday", "Sunday", "Tuesday", "Friday"], correctIndex: 0 },
        { id: "en-dm-q02", type: "qcm", prompt: "Comment dit-on « dimanche » en anglais ?", options: ["Sunday", "Monday", "Saturday", "Thursday"], correctIndex: 0 },
        { id: "en-dm-q03", type: "fill-blank", prompt: "Traduis « mercredi » en anglais : ___", acceptedAnswers: ["wednesday"] },
        { id: "en-dm-q04", type: "qcm", prompt: "Comment dit-on « janvier » en anglais ?", options: ["January", "June", "July", "December"], correctIndex: 0 },
        { id: "en-dm-q05", type: "qcm", prompt: "« December » signifie :", options: ["décembre", "janvier", "octobre", "novembre"], correctIndex: 0 },
        { id: "en-dm-q06", type: "true-false", prompt: "« Sunny » signifie qu'il fait beau et qu'il y a du soleil.", correct: true },
        { id: "en-dm-q07", type: "fill-blank", prompt: "Traduis « il pleut » en anglais : it's ___", acceptedAnswers: ["raining"] },
        { id: "en-dm-q08", type: "qcm", prompt: "« Cold » signifie :", options: ["froid", "chaud", "venteux", "nuageux"], correctIndex: 0 },
        { id: "en-dm-q09", type: "qcm", prompt: "Comment dit-on « samedi » en anglais ?", options: ["Saturday", "Sunday", "Thursday", "Tuesday"], correctIndex: 0 },
      ],
    },
    {
      id: "greetings",
      title: "Greetings & simple phrases",
      description: "Se présenter et utiliser des phrases simples",
      icon: "👋",
      exercises: [
        { id: "en-gr-q01", type: "qcm", prompt: "Comment dit-on « Bonjour » en anglais ?", options: ["Hello", "Goodbye", "Sorry", "Please"], correctIndex: 0 },
        { id: "en-gr-q02", type: "qcm", prompt: "Comment dit-on « Comment vas-tu ? » en anglais ?", options: ["How are you?", "What is this?", "Where are you?", "Who are you?"], correctIndex: 0 },
        { id: "en-gr-q03", type: "fill-blank", prompt: "Traduis « Merci » en anglais : ___", acceptedAnswers: ["thank you", "thanks"] },
        { id: "en-gr-q04", type: "qcm", prompt: "« What is your name? » signifie :", options: ["Comment tu t'appelles ?", "Où habites-tu ?", "Quel âge as-tu ?", "Comment vas-tu ?"], correctIndex: 0 },
        { id: "en-gr-q05", type: "qcm", prompt: "Comment dit-on « Au revoir » en anglais ?", options: ["Goodbye", "Hello", "Please", "Sorry"], correctIndex: 0 },
        { id: "en-gr-q06", type: "true-false", prompt: "« Please » signifie « s'il te plaît ».", correct: true },
        { id: "en-gr-q07", type: "fill-blank", prompt: "Réponds à « What is your name? » par « My name ___ Sany. »", acceptedAnswers: ["is"] },
        { id: "en-gr-q08", type: "qcm", prompt: "« I am fine, thank you » signifie :", options: ["Je vais bien, merci", "Je suis fatigué", "Je m'appelle Léo", "J'ai faim"], correctIndex: 0 },
        { id: "en-gr-q09", type: "qcm", prompt: "Comment dit-on « Quel âge as-tu ? » en anglais ?", options: ["How old are you?", "How are you?", "What time is it?", "Where do you live?"], correctIndex: 0 },
      ],
    },
    {
      id: "school-objects",
      title: "School objects",
      description: "Le matériel scolaire en anglais",
      icon: "🎒",
      exercises: [
        { id: "en-so-q01", type: "qcm", prompt: "Comment dit-on « un cahier » en anglais ?", options: ["a notebook", "a book", "a pencil", "a bag"], correctIndex: 0 },
        { id: "en-so-q02", type: "qcm", prompt: "Comment dit-on « un stylo » en anglais ?", options: ["a pen", "a pencil", "a rubber", "a ruler"], correctIndex: 0 },
        { id: "en-so-q03", type: "fill-blank", prompt: "Traduis « un crayon » en anglais : a ___", acceptedAnswers: ["pencil"] },
        { id: "en-so-q04", type: "qcm", prompt: "« A ruler » signifie :", options: ["une règle", "un cahier", "une gomme", "un sac"], correctIndex: 0 },
        { id: "en-so-q05", type: "qcm", prompt: "Comment dit-on « un sac à dos » en anglais ?", options: ["a backpack", "a basket", "a box", "a bottle"], correctIndex: 0 },
        { id: "en-so-q06", type: "true-false", prompt: "« A rubber » signifie « une gomme » en anglais britannique.", correct: true },
        { id: "en-so-q07", type: "fill-blank", prompt: "Traduis « une trousse » en anglais : a pencil ___", acceptedAnswers: ["case"] },
        { id: "en-so-q08", type: "qcm", prompt: "« A book » signifie :", options: ["un livre", "un cahier", "un stylo", "une table"], correctIndex: 0 },
        { id: "en-so-q09", type: "qcm", prompt: "Comment dit-on « des ciseaux » en anglais ?", options: ["scissors", "scissor", "cutters", "knife"], correctIndex: 0 },
      ],
    },
    {
      id: "house-rooms",
      title: "House & rooms",
      description: "Les pièces de la maison",
      icon: "🏠",
      exercises: [
        { id: "en-hr-q01", type: "qcm", prompt: "Comment dit-on « la cuisine » en anglais ?", options: ["the kitchen", "the bathroom", "the bedroom", "the garden"], correctIndex: 0 },
        { id: "en-hr-q02", type: "qcm", prompt: "Comment dit-on « la chambre » en anglais ?", options: ["the bedroom", "the kitchen", "the living room", "the garage"], correctIndex: 0 },
        { id: "en-hr-q03", type: "fill-blank", prompt: "Traduis « la salle de bain » en anglais : the ___", acceptedAnswers: ["bathroom"] },
        { id: "en-hr-q04", type: "qcm", prompt: "« The living room » signifie :", options: ["le salon", "la cuisine", "le jardin", "le grenier"], correctIndex: 0 },
        { id: "en-hr-q05", type: "qcm", prompt: "Comment dit-on « le jardin » en anglais ?", options: ["the garden", "the garage", "the gate", "the ground"], correctIndex: 0 },
        { id: "en-hr-q06", type: "true-false", prompt: "« The roof » signifie « le toit ».", correct: true },
        { id: "en-hr-q07", type: "fill-blank", prompt: "Traduis « la porte » en anglais : the ___", acceptedAnswers: ["door"] },
        { id: "en-hr-q08", type: "qcm", prompt: "« The window » signifie :", options: ["la fenêtre", "la porte", "le mur", "le toit"], correctIndex: 0 },
        { id: "en-hr-q09", type: "qcm", prompt: "Comment dit-on « l'escalier » en anglais ?", options: ["the stairs", "the floor", "the wall", "the ceiling"], correctIndex: 0 },
      ],
    },
    {
      id: "sports-hobbies",
      title: "Sports & hobbies",
      description: "Les sports et les loisirs",
      icon: "⚽",
      exercises: [
        { id: "en-sh-q01", type: "qcm", prompt: "Comment dit-on « le football » en anglais ?", options: ["football", "basketball", "tennis", "swimming"], correctIndex: 0 },
        { id: "en-sh-q02", type: "qcm", prompt: "Comment dit-on « nager » en anglais ?", options: ["to swim", "to run", "to jump", "to dance"], correctIndex: 0 },
        { id: "en-sh-q03", type: "fill-blank", prompt: "Traduis « danser » en anglais : to ___", acceptedAnswers: ["dance"] },
        { id: "en-sh-q04", type: "qcm", prompt: "« To read » signifie :", options: ["lire", "courir", "chanter", "dessiner"], correctIndex: 0 },
        { id: "en-sh-q05", type: "qcm", prompt: "Comment dit-on « le vélo » en anglais ?", options: ["bike", "ball", "boat", "board"], correctIndex: 0 },
        { id: "en-sh-q06", type: "true-false", prompt: "« To play » peut se traduire par « jouer ».", correct: true },
        { id: "en-sh-q07", type: "fill-blank", prompt: "Traduis « dessiner » en anglais : to ___", acceptedAnswers: ["draw"] },
        { id: "en-sh-q08", type: "qcm", prompt: "« To sing » signifie :", options: ["chanter", "sauter", "courir", "peindre"], correctIndex: 0 },
        { id: "en-sh-q09", type: "qcm", prompt: "Comment dit-on « le basket-ball » en anglais ?", options: ["basketball", "football", "baseball", "volleyball"], correctIndex: 0 },
      ],
    },
    {
      id: "telling-time",
      title: "Telling time",
      description: "Dire et comprendre l'heure en anglais",
      icon: "🕐",
      exercises: [
        { id: "en-tt-q01", type: "qcm", prompt: "Comment dit-on « Quelle heure est-il ? » en anglais ?", options: ["What time is it?", "What is your name?", "How are you?", "Where is it?"], correctIndex: 0 },
        { id: "en-tt-q02", type: "qcm", prompt: "« It's three o'clock » signifie :", options: ["Il est trois heures", "Il est trois jours", "Il fait trois degrés", "Il y a trois enfants"], correctIndex: 0 },
        { id: "en-tt-q03", type: "fill-blank", prompt: "Traduis « midi » en anglais : ___", acceptedAnswers: ["noon"] },
        { id: "en-tt-q04", type: "qcm", prompt: "Comment dit-on « il est minuit » en anglais ?", options: ["It's midnight", "It's midday", "It's morning", "It's evening"], correctIndex: 0 },
        { id: "en-tt-q05", type: "true-false", prompt: "« Half past two » signifie « deux heures et demie ».", correct: true },
        { id: "en-tt-q06", type: "qcm", prompt: "« Quarter past four » signifie :", options: ["quatre heures et quart", "quatre heures moins le quart", "quatre heures et demie", "quatre heures"], correctIndex: 0 },
        { id: "en-tt-q07", type: "fill-blank", prompt: "Traduis « le matin » en anglais : in the ___", acceptedAnswers: ["morning"] },
        { id: "en-tt-q08", type: "qcm", prompt: "Comment dit-on « le soir » en anglais ?", options: ["evening", "morning", "afternoon", "night"], correctIndex: 0 },
      ],
    },
    {
      id: "transport",
      title: "Transport",
      description: "Les moyens de transport en anglais",
      icon: "🚌",
      exercises: [
        { id: "en-tr-q01", type: "qcm", prompt: "Comment dit-on « une voiture » en anglais ?", options: ["a car", "a bike", "a bus", "a train"], correctIndex: 0 },
        { id: "en-tr-q02", type: "qcm", prompt: "Comment dit-on « un bus » en anglais ?", options: ["a bus", "a boat", "a plane", "a train"], correctIndex: 0 },
        { id: "en-tr-q03", type: "fill-blank", prompt: "Traduis « un avion » en anglais : a ___", acceptedAnswers: ["plane"] },
        { id: "en-tr-q04", type: "qcm", prompt: "« A train » signifie :", options: ["un train", "un bus", "un bateau", "une voiture"], correctIndex: 0 },
        { id: "en-tr-q05", type: "true-false", prompt: "« A boat » signifie « un bateau ».", correct: true },
        { id: "en-tr-q06", type: "qcm", prompt: "Comment dit-on « à pied » en anglais ?", options: ["on foot", "by car", "by bike", "by bus"], correctIndex: 0 },
        { id: "en-tr-q07", type: "fill-blank", prompt: "Traduis « à vélo » en anglais : by ___", acceptedAnswers: ["bike"] },
        { id: "en-tr-q08", type: "qcm", prompt: "« How do you go to school? I go by bus. » signifie :", options: ["Je vais en bus", "Je vais à pied", "Je vais en voiture", "Je vais en train"], correctIndex: 0 },
        { id: "en-tr-q09", type: "qcm", prompt: "Comment dit-on « le métro » en anglais ?", options: ["the subway", "the train", "the bus", "the tram"], correctIndex: 0 },
      ],
    },
    {
      id: "daily-routine",
      title: "Daily routine",
      description: "Décrire sa journée en anglais",
      icon: "⏰",
      exercises: [
        { id: "en-dr-q01", type: "qcm", prompt: "Comment dit-on « se réveiller » en anglais ?", options: ["to wake up", "to sleep", "to eat", "to wash"], correctIndex: 0 },
        { id: "en-dr-q02", type: "qcm", prompt: "Comment dit-on « se brosser les dents » en anglais ?", options: ["to brush your teeth", "to wash your hands", "to comb your hair", "to take a shower"], correctIndex: 0 },
        { id: "en-dr-q03", type: "fill-blank", prompt: "Traduis « se lever » en anglais : to get ___", acceptedAnswers: ["up"] },
        { id: "en-dr-q04", type: "qcm", prompt: "« I have breakfast at 7am » signifie :", options: ["Je prends mon petit-déjeuner à 7h", "Je me réveille à 7h", "Je me lave à 7h", "Je dors à 7h"], correctIndex: 0 },
        { id: "en-dr-q05", type: "true-false", prompt: "« To go to bed » signifie « aller se coucher ».", correct: true },
        { id: "en-dr-q06", type: "qcm", prompt: "Comment dit-on « prendre une douche » en anglais ?", options: ["to take a shower", "to take a bath", "to wash up", "to clean up"], correctIndex: 0 },
        { id: "en-dr-q07", type: "fill-blank", prompt: "Traduis « s'habiller » en anglais : to get ___", acceptedAnswers: ["dressed"] },
        { id: "en-dr-q08", type: "qcm", prompt: "« What time do you go to school? » demande :", options: ["à quelle heure tu vas à l'école", "comment tu vas à l'école", "où est l'école", "qui va à l'école"], correctIndex: 0 },
        { id: "en-dr-q09", type: "true-false", prompt: "« To do homework » signifie « faire les devoirs ».", correct: true },
      ],
    },
  ],
};
