import type { Subject } from "../types";

export const anglaisCm1: Subject = {
  id: "anglais-cm1",
  name: "Anglais",
  icon: "🇬🇧",
  colorFrom: "from-violet-500",
  colorTo: "to-purple-600",
  chapters: [
    {
      id: "colors-numbers",
      title: "Colors & Numbers",
      description: "Les couleurs et les nombres jusqu'à 20",
      icon: "🎨",
      exercises: [
        { id: "en-cn-q01", type: "qcm", prompt: "Comment dit-on « rouge » en anglais ?", options: ["red", "blue", "green", "black"], correctIndex: 0 },
        { id: "en-cn-q02", type: "qcm", prompt: "Comment dit-on « bleu » en anglais ?", options: ["blue", "yellow", "white", "brown"], correctIndex: 0 },
        { id: "en-cn-q03", type: "fill-blank", prompt: "Traduis « jaune » en anglais : ___", acceptedAnswers: ["yellow"] },
        { id: "en-cn-q04", type: "qcm", prompt: "Comment dit-on « sept » en anglais ?", options: ["seven", "six", "eight", "seventeen"], correctIndex: 0 },
        { id: "en-cn-q05", type: "qcm", prompt: "« Twelve » signifie :", options: ["douze", "deux", "vingt", "dix"], correctIndex: 0 },
        { id: "en-cn-q06", type: "true-false", prompt: "« Green » signifie « vert ».", correct: true },
        { id: "en-cn-q07", type: "fill-blank", prompt: "Traduis « quinze » en anglais : ___", acceptedAnswers: ["fifteen"] },
        { id: "en-cn-q08", type: "qcm", prompt: "Comment dit-on « noir » en anglais ?", options: ["black", "white", "pink", "purple"], correctIndex: 0 },
        { id: "en-cn-q09", type: "qcm", prompt: "« Twenty » signifie :", options: ["vingt", "deux", "douze", "dix"], correctIndex: 0 },
        { id: "en-cn-q10", type: "true-false", prompt: "« Orange » se dit pareil en français et en anglais.", correct: true },
      ],
    },
    {
      id: "animals",
      title: "Animals",
      description: "Le nom des animaux en anglais",
      icon: "🐶",
      exercises: [
        { id: "en-an-q01", type: "qcm", prompt: "Comment dit-on « chien » en anglais ?", options: ["dog", "cat", "bird", "fish"], correctIndex: 0 },
        { id: "en-an-q02", type: "qcm", prompt: "Comment dit-on « chat » en anglais ?", options: ["cat", "dog", "cow", "duck"], correctIndex: 0 },
        { id: "en-an-q03", type: "fill-blank", prompt: "Traduis « oiseau » en anglais : ___", acceptedAnswers: ["bird"] },
        { id: "en-an-q04", type: "qcm", prompt: "« Horse » signifie :", options: ["cheval", "vache", "mouton", "cochon"], correctIndex: 0 },
        { id: "en-an-q05", type: "qcm", prompt: "Comment dit-on « lapin » en anglais ?", options: ["rabbit", "rat", "rooster", "raccoon"], correctIndex: 0 },
        { id: "en-an-q06", type: "true-false", prompt: "« Fish » signifie « poisson ».", correct: true },
        { id: "en-an-q07", type: "fill-blank", prompt: "Traduis « vache » en anglais : ___", acceptedAnswers: ["cow"] },
        { id: "en-an-q08", type: "qcm", prompt: "« Mouse » signifie :", options: ["souris", "moustique", "mouche", "ours"], correctIndex: 0 },
        { id: "en-an-q09", type: "qcm", prompt: "Comment dit-on « mouton » en anglais ?", options: ["sheep", "ship", "shop", "shoe"], correctIndex: 0 },
        { id: "en-an-q10", type: "true-false", prompt: "« Duck » signifie « canard ».", correct: true },
      ],
    },
    {
      id: "family",
      title: "Family",
      description: "Les membres de la famille",
      icon: "👨‍👩‍👧",
      exercises: [
        { id: "en-fa-q01", type: "qcm", prompt: "Comment dit-on « maman » en anglais ?", options: ["mum", "dad", "sister", "brother"], correctIndex: 0 },
        { id: "en-fa-q02", type: "qcm", prompt: "Comment dit-on « papa » en anglais ?", options: ["dad", "mum", "aunt", "uncle"], correctIndex: 0 },
        { id: "en-fa-q03", type: "fill-blank", prompt: "Traduis « frère » en anglais : ___", acceptedAnswers: ["brother"] },
        { id: "en-fa-q04", type: "qcm", prompt: "« Sister » signifie :", options: ["sœur", "frère", "cousine", "tante"], correctIndex: 0 },
        { id: "en-fa-q05", type: "qcm", prompt: "Comment dit-on « grand-père » en anglais ?", options: ["grandfather", "grandmother", "father", "uncle"], correctIndex: 0 },
        { id: "en-fa-q06", type: "true-false", prompt: "« Grandmother » signifie « grand-mère ».", correct: true },
        { id: "en-fa-q07", type: "fill-blank", prompt: "Traduis « oncle » en anglais : ___", acceptedAnswers: ["uncle"] },
        { id: "en-fa-q08", type: "qcm", prompt: "« Aunt » signifie :", options: ["tante", "oncle", "cousin", "nièce"], correctIndex: 0 },
        { id: "en-fa-q09", type: "qcm", prompt: "Comment dit-on « les parents » en anglais ?", options: ["parents", "family", "children", "kids"], correctIndex: 0 },
      ],
    },
    {
      id: "body-clothes",
      title: "Body & Clothes",
      description: "Les parties du corps et les vêtements",
      icon: "👕",
      exercises: [
        { id: "en-bc-q01", type: "qcm", prompt: "Comment dit-on « tête » en anglais ?", options: ["head", "hand", "foot", "eye"], correctIndex: 0 },
        { id: "en-bc-q02", type: "qcm", prompt: "Comment dit-on « main » en anglais ?", options: ["hand", "head", "hair", "ear"], correctIndex: 0 },
        { id: "en-bc-q03", type: "fill-blank", prompt: "Traduis « pied » en anglais : ___", acceptedAnswers: ["foot"] },
        { id: "en-bc-q04", type: "qcm", prompt: "« Eyes » signifie :", options: ["yeux", "oreilles", "mains", "pieds"], correctIndex: 0 },
        { id: "en-bc-q05", type: "qcm", prompt: "Comment dit-on « chaussures » en anglais ?", options: ["shoes", "shirt", "shorts", "hat"], correctIndex: 0 },
        { id: "en-bc-q06", type: "true-false", prompt: "« T-shirt » se dit presque pareil en français et en anglais.", correct: true },
        { id: "en-bc-q07", type: "fill-blank", prompt: "Traduis « pantalon » en anglais : ___", acceptedAnswers: ["trousers", "pants"] },
        { id: "en-bc-q08", type: "qcm", prompt: "« Hat » signifie :", options: ["chapeau", "veste", "robe", "ceinture"], correctIndex: 0 },
        { id: "en-bc-q09", type: "qcm", prompt: "Comment dit-on « chaussettes » en anglais ?", options: ["socks", "shoes", "shorts", "scarf"], correctIndex: 0 },
      ],
    },
    {
      id: "food",
      title: "Food",
      description: "Les aliments et les repas",
      icon: "🍎",
      exercises: [
        { id: "en-fo-q01", type: "qcm", prompt: "Comment dit-on « pomme » en anglais ?", options: ["apple", "banana", "bread", "milk"], correctIndex: 0 },
        { id: "en-fo-q02", type: "qcm", prompt: "Comment dit-on « pain » en anglais ?", options: ["bread", "butter", "cheese", "cake"], correctIndex: 0 },
        { id: "en-fo-q03", type: "fill-blank", prompt: "Traduis « lait » en anglais : ___", acceptedAnswers: ["milk"] },
        { id: "en-fo-q04", type: "qcm", prompt: "« Cheese » signifie :", options: ["fromage", "beurre", "œuf", "sucre"], correctIndex: 0 },
        { id: "en-fo-q05", type: "qcm", prompt: "Comment dit-on « eau » en anglais ?", options: ["water", "juice", "tea", "soup"], correctIndex: 0 },
        { id: "en-fo-q06", type: "true-false", prompt: "« Chocolate » signifie « chocolat ».", correct: true },
        { id: "en-fo-q07", type: "fill-blank", prompt: "Traduis « banane » en anglais : ___", acceptedAnswers: ["banana"] },
        { id: "en-fo-q08", type: "qcm", prompt: "« Egg » signifie :", options: ["œuf", "lait", "fromage", "pain"], correctIndex: 0 },
        { id: "en-fo-q09", type: "qcm", prompt: "Comment dit-on « petit-déjeuner » en anglais ?", options: ["breakfast", "lunch", "dinner", "snack"], correctIndex: 0 },
      ],
    },
    {
      id: "days-months",
      title: "Days, months & weather",
      description: "Les jours, les mois et le temps qu'il fait",
      icon: "📅",
      exercises: [
        { id: "en-dm-q01", type: "qcm", prompt: "Comment dit-on « lundi » en anglais ?", options: ["Monday", "Sunday", "Tuesday", "Friday"], correctIndex: 0 },
        { id: "en-dm-q02", type: "qcm", prompt: "Comment dit-on « dimanche » en anglais ?", options: ["Sunday", "Monday", "Saturday", "Thursday"], correctIndex: 0 },
        { id: "en-dm-q03", type: "fill-blank", prompt: "Traduis « mercredi » en anglais : ___", acceptedAnswers: ["wednesday"] },
        { id: "en-dm-q04", type: "qcm", prompt: "Comment dit-on « janvier » en anglais ?", options: ["January", "June", "July", "December"], correctIndex: 0 },
        { id: "en-dm-q05", type: "qcm", prompt: "« December » signifie :", options: ["décembre", "janvier", "octobre", "novembre"], correctIndex: 0 },
        { id: "en-dm-q06", type: "true-false", prompt: "« Sunny » signifie qu'il fait beau et qu'il y a du soleil.", correct: true },
        { id: "en-dm-q07", type: "fill-blank", prompt: "Traduis « il pleut » en anglais : it's ___", acceptedAnswers: ["raining"] },
        { id: "en-dm-q08", type: "qcm", prompt: "« Cold » signifie :", options: ["froid", "chaud", "venteux", "nuageux"], correctIndex: 0 },
        { id: "en-dm-q09", type: "qcm", prompt: "Comment dit-on « samedi » en anglais ?", options: ["Saturday", "Sunday", "Thursday", "Tuesday"], correctIndex: 0 },
      ],
    },
    {
      id: "greetings",
      title: "Greetings & simple phrases",
      description: "Se présenter et utiliser des phrases simples",
      icon: "👋",
      exercises: [
        { id: "en-gr-q01", type: "qcm", prompt: "Comment dit-on « Bonjour » en anglais ?", options: ["Hello", "Goodbye", "Sorry", "Please"], correctIndex: 0 },
        { id: "en-gr-q02", type: "qcm", prompt: "Comment dit-on « Comment vas-tu ? » en anglais ?", options: ["How are you?", "What is this?", "Where are you?", "Who are you?"], correctIndex: 0 },
        { id: "en-gr-q03", type: "fill-blank", prompt: "Traduis « Merci » en anglais : ___", acceptedAnswers: ["thank you", "thanks"] },
        { id: "en-gr-q04", type: "qcm", prompt: "« What is your name? » signifie :", options: ["Comment tu t'appelles ?", "Où habites-tu ?", "Quel âge as-tu ?", "Comment vas-tu ?"], correctIndex: 0 },
        { id: "en-gr-q05", type: "qcm", prompt: "Comment dit-on « Au revoir » en anglais ?", options: ["Goodbye", "Hello", "Please", "Sorry"], correctIndex: 0 },
        { id: "en-gr-q06", type: "true-false", prompt: "« Please » signifie « s'il te plaît ».", correct: true },
        { id: "en-gr-q07", type: "fill-blank", prompt: "Réponds à « What is your name? » par « My name ___ Sany. »", acceptedAnswers: ["is"] },
        { id: "en-gr-q08", type: "qcm", prompt: "« I am fine, thank you » signifie :", options: ["Je vais bien, merci", "Je suis fatigué", "Je m'appelle Léo", "J'ai faim"], correctIndex: 0 },
        { id: "en-gr-q09", type: "qcm", prompt: "Comment dit-on « Quel âge as-tu ? » en anglais ?", options: ["How old are you?", "How are you?", "What time is it?", "Where do you live?"], correctIndex: 0 },
      ],
    },
  ],
};
