import type { Subject } from "../types";

export const francaisCm1: Subject = {
  id: "francais-cm1",
  name: "Français",
  icon: "📖",
  colorFrom: "from-rose-500",
  colorTo: "to-orange-500",
  chapters: [
    {
      id: "nature-des-mots",
      title: "Nature des mots",
      description: "Noms, verbes, adjectifs et déterminants",
      icon: "🔤",
      exercises: [
        { id: "fr-nm-q01", type: "qcm", prompt: "Dans « le petit chat dort », quel mot est un adjectif ?", options: ["petit", "chat", "dort", "le"], correctIndex: 0 },
        { id: "fr-nm-q02", type: "qcm", prompt: "Quel mot est un verbe dans « elle chante une chanson » ?", options: ["chante", "elle", "une", "chanson"], correctIndex: 0 },
        { id: "fr-nm-q03", type: "true-false", prompt: "« table » est un nom commun.", correct: true },
        { id: "fr-nm-q04", type: "qcm", prompt: "Quel est le déterminant dans « les enfants jouent » ?", options: ["les", "enfants", "jouent", "aucun"], correctIndex: 0 },
        { id: "fr-nm-q05", type: "fill-blank", prompt: "Dans « Paris est une grande ville », le mot « Paris » est un nom ___ (commun ou propre).", acceptedAnswers: ["propre"] },
        { id: "fr-nm-q06", type: "qcm", prompt: "Quel mot est un adjectif dans « une jolie maison bleue » ?", options: ["jolie", "maison", "une", "et"], correctIndex: 0 },
        { id: "fr-nm-q07", type: "true-false", prompt: "Un verbe peut se conjuguer.", correct: true },
        { id: "fr-nm-q08", type: "qcm", prompt: "Quelle est la nature du mot souligné : « il COURT vite » ?", options: ["un verbe", "un nom", "un adjectif", "un déterminant"], correctIndex: 0 },
        { id: "fr-nm-q09", type: "qcm", prompt: "Lequel de ces mots est un pronom ?", options: ["elle", "rapide", "maison", "chanter"], correctIndex: 0 },
        { id: "fr-nm-q10", type: "true-false", prompt: "Un adjectif qualificatif donne une précision sur un nom.", correct: true },
      ],
    },
    {
      id: "conjugaison-present",
      title: "Conjugaison : le présent",
      description: "Conjuguer au présent les verbes courants",
      icon: "📝",
      exercises: [
        { id: "fr-cp-q01", type: "qcm", prompt: "Conjugue « chanter » au présent avec « je » :", options: ["je chante", "je chantes", "je chantons", "je chantai"], correctIndex: 0 },
        { id: "fr-cp-q02", type: "qcm", prompt: "Conjugue « avoir » au présent avec « nous » :", options: ["nous avons", "nous avez", "nous ai", "nous a"], correctIndex: 0 },
        { id: "fr-cp-q03", type: "fill-blank", prompt: "Conjugue « être » au présent avec « tu » : tu ___", acceptedAnswers: ["es"] },
        { id: "fr-cp-q04", type: "qcm", prompt: "Conjugue « aller » au présent avec « ils » :", options: ["ils vont", "ils allent", "ils va", "ils allons"], correctIndex: 0 },
        { id: "fr-cp-q05", type: "true-false", prompt: "Au présent, avec « il/elle », les verbes en -er se terminent par -e.", correct: true },
        { id: "fr-cp-q06", type: "qcm", prompt: "Conjugue « finir » au présent avec « vous » :", options: ["vous finissez", "vous finez", "vous finissont", "vous finis"], correctIndex: 0 },
        { id: "fr-cp-q07", type: "fill-blank", prompt: "Conjugue « faire » au présent avec « je » : je ___", acceptedAnswers: ["fais"] },
        { id: "fr-cp-q08", type: "qcm", prompt: "Quelle phrase est correctement conjuguée au présent ?", options: ["Elle joue dans le jardin.", "Elle jouent dans le jardin.", "Elle jouez dans le jardin.", "Elle jouons dans le jardin."], correctIndex: 0 },
        { id: "fr-cp-q09", type: "true-false", prompt: "« Je peux » est la conjugaison correcte du verbe « pouvoir » au présent avec « je ».", correct: true },
        { id: "fr-cp-q10", type: "qcm", prompt: "Conjugue « venir » au présent avec « tu » :", options: ["tu viens", "tu vient", "tu venez", "tu venons"], correctIndex: 0 },
      ],
    },
    {
      id: "conjugaison-futur-imparfait",
      title: "Conjugaison : futur et imparfait",
      description: "Conjuguer les verbes courants à ces deux temps",
      icon: "🕰️",
      exercises: [
        { id: "fr-fi-q01", type: "qcm", prompt: "Conjugue « jouer » au futur avec « je » :", options: ["je jouerai", "je jouais", "je joue", "je jouerais"], correctIndex: 0 },
        { id: "fr-fi-q02", type: "qcm", prompt: "Conjugue « chanter » à l'imparfait avec « il » :", options: ["il chantait", "il chanta", "il chantera", "il chante"], correctIndex: 0 },
        { id: "fr-fi-q03", type: "fill-blank", prompt: "Conjugue « avoir » au futur avec « nous » : nous ___", acceptedAnswers: ["aurons"] },
        { id: "fr-fi-q04", type: "true-false", prompt: "L'imparfait sert souvent à décrire ou à raconter une habitude dans le passé.", correct: true },
        { id: "fr-fi-q05", type: "qcm", prompt: "Conjugue « être » à l'imparfait avec « tu » :", options: ["tu étais", "tu seras", "tu es", "tu fus"], correctIndex: 0 },
        { id: "fr-fi-q06", type: "qcm", prompt: "Conjugue « manger » au futur avec « ils » :", options: ["ils mangeront", "ils mangeaient", "ils mangent", "ils mangèrent"], correctIndex: 0 },
        { id: "fr-fi-q07", type: "fill-blank", prompt: "Conjugue « aller » à l'imparfait avec « je » : j'___", acceptedAnswers: ["allais"] },
        { id: "fr-fi-q08", type: "true-false", prompt: "Au futur, tous les verbes du 1er groupe se terminent par -erai, -eras, -era... avec « je, tu, il »", correct: true },
        { id: "fr-fi-q09", type: "qcm", prompt: "Quelle phrase est au futur ?", options: ["Demain, nous partirons en vacances.", "Hier, nous partions en vacances.", "Nous partons en vacances.", "Nous étions en vacances."], correctIndex: 0 },
        { id: "fr-fi-q10", type: "qcm", prompt: "Conjugue « finir » au futur avec « elle » :", options: ["elle finira", "elle finissait", "elle finit", "elle finirait"], correctIndex: 0 },
      ],
    },
    {
      id: "accords",
      title: "Accords",
      description: "Pluriels des noms et accord des adjectifs",
      icon: "🔗",
      exercises: [
        { id: "fr-ac-q01", type: "qcm", prompt: "Quel est le pluriel de « un cheval » ?", options: ["des chevaux", "des chevals", "des chevaus", "des cheval"], correctIndex: 0 },
        { id: "fr-ac-q02", type: "qcm", prompt: "Quel est le pluriel de « un chou » ?", options: ["des choux", "des chous", "des choues", "des chou"], correctIndex: 0 },
        { id: "fr-ac-q03", type: "fill-blank", prompt: "Accorde : « une jolie fleur ___ » (fleur au pluriel : des jolies fleur___)", acceptedAnswers: ["s"] },
        { id: "fr-ac-q04", type: "true-false", prompt: "Le verbe s'accorde toujours avec son sujet.", correct: true },
        { id: "fr-ac-q05", type: "qcm", prompt: "Choisis l'accord correct : « Les enfants ___ contents. »", options: ["sont", "est", "es", "soient"], correctIndex: 0 },
        { id: "fr-ac-q06", type: "qcm", prompt: "Quel est le féminin de « un grand chat » ?", options: ["une grande chatte", "un grande chat", "une grand chatte", "une grande chat"], correctIndex: 0 },
        { id: "fr-ac-q07", type: "fill-blank", prompt: "« Les chats ___ noirs. » (verbe être au présent)", acceptedAnswers: ["sont"] },
        { id: "fr-ac-q08", type: "true-false", prompt: "« Des beaux jardins » est correctement accordé.", correct: true },
        { id: "fr-ac-q09", type: "qcm", prompt: "Quel est le pluriel de « un journal » ?", options: ["des journaux", "des journals", "des journales", "des journau"], correctIndex: 0 },
        { id: "fr-ac-q10", type: "qcm", prompt: "Accorde : « Marie et Léa ___ arrivées. »", options: ["sont", "est", "es", "a"], correctIndex: 0 },
      ],
    },
    {
      id: "homophones",
      title: "Homophones grammaticaux",
      description: "a/à, et/est, son/sont, ce/se, ou/où",
      icon: "🤔",
      exercises: [
        { id: "fr-ho-q01", type: "qcm", prompt: "Complète : « Il ___ allé au parc. »", options: ["est", "et", "es", "ai"], correctIndex: 0 },
        { id: "fr-ho-q02", type: "qcm", prompt: "Complète : « Léa ___ Tom jouent ensemble. »", options: ["et", "est", "es", "ai"], correctIndex: 0 },
        { id: "fr-ho-q03", type: "fill-blank", prompt: "Complète : « Il a perdu ___ ballon. » (a ou à ?)", acceptedAnswers: ["a"] },
        { id: "fr-ho-q04", type: "qcm", prompt: "Complète : « Je vais ___ l'école. »", options: ["à", "a", "as", "ah"], correctIndex: 0 },
        { id: "fr-ho-q05", type: "true-false", prompt: "« Son chien et sa chatte sont dans le jardin » utilise correctement « son » et « sont ».", correct: true },
        { id: "fr-ho-q06", type: "qcm", prompt: "Complète : « Les enfants ___ dans la cour. »", options: ["sont", "son", "s'ont", "s'on"], correctIndex: 0 },
        { id: "fr-ho-q07", type: "qcm", prompt: "Complète : « Le chat lave ___ pelage. »", options: ["son", "sont", "s'on", "sons"], correctIndex: 0 },
        { id: "fr-ho-q08", type: "fill-blank", prompt: "Complète : « ___ chien aboie fort. » (ce ou se ?)", acceptedAnswers: ["ce"] },
        { id: "fr-ho-q09", type: "qcm", prompt: "Complète : « Il ___ lave les mains. »", options: ["se", "ce", "ceux", "sai"], correctIndex: 0 },
        { id: "fr-ho-q10", type: "qcm", prompt: "Complète : « Tu préfères les pommes ___ les poires ? »", options: ["ou", "où", "houx", "août"], correctIndex: 0 },
        { id: "fr-ho-q11", type: "qcm", prompt: "Complète : « ___ est la maison de Théo ? »", options: ["Où", "Ou", "Houx", "Août"], correctIndex: 0 },
      ],
    },
    {
      id: "vocabulaire",
      title: "Vocabulaire",
      description: "Synonymes, antonymes et familles de mots",
      icon: "📚",
      exercises: [
        { id: "fr-vo-q01", type: "qcm", prompt: "Quel mot est un synonyme de « content » ?", options: ["heureux", "triste", "fatigué", "grand"], correctIndex: 0 },
        { id: "fr-vo-q02", type: "qcm", prompt: "Quel mot est l'antonyme (contraire) de « grand » ?", options: ["petit", "joli", "rapide", "lourd"], correctIndex: 0 },
        { id: "fr-vo-q03", type: "fill-blank", prompt: "Le contraire de « chaud » est ___.", acceptedAnswers: ["froid"] },
        { id: "fr-vo-q04", type: "qcm", prompt: "Quel mot appartient à la famille de « terre » ?", options: ["atterrir", "terrible", "terrasse vide", "terne"], correctIndex: 0 },
        { id: "fr-vo-q05", type: "true-false", prompt: "« rapide » et « lent » sont des antonymes.", correct: true },
        { id: "fr-vo-q06", type: "qcm", prompt: "Quel mot est un synonyme de « commencer » ?", options: ["débuter", "finir", "arrêter", "dormir"], correctIndex: 0 },
        { id: "fr-vo-q07", type: "fill-blank", prompt: "Le synonyme de « rapide » est ___.", acceptedAnswers: ["vite", "véloce"] },
        { id: "fr-vo-q08", type: "qcm", prompt: "Quel mot fait partie de la famille de « chant » ?", options: ["chanteur", "champ", "chance", "chaud"], correctIndex: 0 },
        { id: "fr-vo-q09", type: "true-false", prompt: "« beau » et « joli » peuvent être des synonymes.", correct: true },
        { id: "fr-vo-q10", type: "qcm", prompt: "Quel est l'antonyme de « monter » ?", options: ["descendre", "sauter", "courir", "voler"], correctIndex: 0 },
      ],
    },
    {
      id: "la-phrase",
      title: "La phrase et la ponctuation",
      description: "Types de phrases et ponctuation",
      icon: "❓",
      exercises: [
        { id: "fr-ph-q01", type: "qcm", prompt: "« Quel âge as-tu ? » est une phrase :", options: ["interrogative", "déclarative", "exclamative", "impérative"], correctIndex: 0 },
        { id: "fr-ph-q02", type: "qcm", prompt: "« Quelle belle journée ! » est une phrase :", options: ["exclamative", "interrogative", "déclarative", "négative"], correctIndex: 0 },
        { id: "fr-ph-q03", type: "true-false", prompt: "Une phrase déclarative se termine par un point.", correct: true },
        { id: "fr-ph-q04", type: "fill-blank", prompt: "Une phrase interrogative se termine par un point ___.", acceptedAnswers: ["d'interrogation"] },
        { id: "fr-ph-q05", type: "qcm", prompt: "« Range ta chambre ! » est une phrase :", options: ["impérative", "interrogative", "déclarative", "exclamative seulement"], correctIndex: 0 },
        { id: "fr-ph-q06", type: "qcm", prompt: "Toute phrase commence par :", options: ["une majuscule", "une minuscule", "un chiffre", "un tiret"], correctIndex: 0 },
        { id: "fr-ph-q07", type: "true-false", prompt: "« Le chat dort. » est une phrase négative.", correct: false, explanation: "C'est une phrase affirmative. La forme négative serait « Le chat ne dort pas. »" },
        { id: "fr-ph-q08", type: "qcm", prompt: "Quelle est la forme négative de « Il aime les épinards. » ?", options: ["Il n'aime pas les épinards.", "Il aime pas les épinards.", "Il aime les épinards pas.", "Il n'aime les épinards."], correctIndex: 0 },
        { id: "fr-ph-q09", type: "qcm", prompt: "Dans une phrase, le sujet fait l'action. Quel est le sujet de « Le chien mange sa pâtée. » ?", options: ["Le chien", "mange", "sa pâtée", "aucun"], correctIndex: 0 },
      ],
    },
    {
      id: "conjugaison-passe-compose",
      title: "Conjugaison : le passé composé",
      description: "Conjuguer avec avoir et être au passé composé",
      icon: "⏳",
      exercises: [
        { id: "fr-pc-q01", type: "qcm", prompt: "Conjugue « jouer » au passé composé avec « je » :", options: ["j'ai joué", "je jouai", "je joue", "j'avais joué"], correctIndex: 0 },
        { id: "fr-pc-q02", type: "qcm", prompt: "Conjugue « aller » au passé composé avec « elle » :", options: ["elle est allée", "elle a allé", "elle allait", "elle ira"], correctIndex: 0 },
        { id: "fr-pc-q03", type: "fill-blank", prompt: "Le passé composé se forme avec l'auxiliaire avoir ou être suivi du ___.", acceptedAnswers: ["participe passé"] },
        { id: "fr-pc-q04", type: "true-false", prompt: "Avec l'auxiliaire être, le participe passé s'accorde avec le sujet.", correct: true },
        { id: "fr-pc-q05", type: "qcm", prompt: "Conjugue « manger » au passé composé avec « nous » :", options: ["nous avons mangé", "nous mangeons", "nous mangions", "nous mangerons"], correctIndex: 0 },
        { id: "fr-pc-q06", type: "qcm", prompt: "Quel est le participe passé du verbe « faire » ?", options: ["fait", "fais", "faisait", "ferai"], correctIndex: 0 },
        { id: "fr-pc-q07", type: "fill-blank", prompt: "Conjugue « venir » au passé composé avec « il » : il ___ venu", acceptedAnswers: ["est"] },
        { id: "fr-pc-q08", type: "true-false", prompt: "« J'ai parti » est correctement conjugué.", correct: false, explanation: "Le verbe partir se conjugue avec être : « je suis parti »." },
        { id: "fr-pc-q09", type: "qcm", prompt: "Quelle phrase est au passé composé ?", options: ["Hier, j'ai mangé une pomme.", "Demain, je mangerai une pomme.", "Je mange une pomme.", "Je mangeais une pomme."], correctIndex: 0 },
      ],
    },
    {
      id: "groupe-nominal",
      title: "Le groupe nominal",
      description: "Déterminant, nom et adjectif : les accords",
      icon: "🧱",
      exercises: [
        { id: "fr-gn-q01", type: "qcm", prompt: "Dans « le grand chat noir », le nom noyau est :", options: ["chat", "grand", "noir", "le"], correctIndex: 0 },
        { id: "fr-gn-q02", type: "qcm", prompt: "Combien de groupes nominaux dans « Le chien et le chat dorment. » ?", options: ["2", "1", "3", "4"], correctIndex: 0 },
        { id: "fr-gn-q03", type: "fill-blank", prompt: "Dans le groupe nominal, le déterminant et l'adjectif s'accordent en genre et en ___ avec le nom.", acceptedAnswers: ["nombre"] },
        { id: "fr-gn-q04", type: "true-false", prompt: "« une belle maison » est un groupe nominal.", correct: true },
        { id: "fr-gn-q05", type: "qcm", prompt: "Quel groupe nominal est correctement accordé ?", options: ["des petites fleurs", "des petite fleurs", "des petits fleurs", "des petite fleur"], correctIndex: 0 },
        { id: "fr-gn-q06", type: "qcm", prompt: "Dans « mes deux meilleures amies », le nom noyau est :", options: ["amies", "deux", "meilleures", "mes"], correctIndex: 0 },
        { id: "fr-gn-q07", type: "true-false", prompt: "Un groupe nominal peut être réduit à un seul nom.", correct: true },
        { id: "fr-gn-q08", type: "qcm", prompt: "Complète : « un ___ garçon » (joli, masculin singulier)", options: ["joli", "jolie", "jolis", "jolies"], correctIndex: 0 },
      ],
    },
    {
      id: "dictionnaire",
      title: "Le dictionnaire",
      description: "Ordre alphabétique et lecture d'une définition",
      icon: "📔",
      exercises: [
        { id: "fr-di-q01", type: "qcm", prompt: "Dans le dictionnaire, les mots sont rangés :", options: ["par ordre alphabétique", "par longueur", "par thème", "au hasard"], correctIndex: 0 },
        { id: "fr-di-q02", type: "qcm", prompt: "Quel mot vient en premier dans l'ordre alphabétique ?", options: ["abeille", "cheval", "chat", "banane"], correctIndex: 0 },
        { id: "fr-di-q03", type: "fill-blank", prompt: "Dans le dictionnaire, une entrée donne la nature du mot et sa ___.", acceptedAnswers: ["définition"] },
        { id: "fr-di-q04", type: "true-false", prompt: "Le dictionnaire donne uniquement l'orthographe des mots, jamais leur sens.", correct: false, explanation: "Le dictionnaire donne aussi le sens (la définition) des mots." },
        { id: "fr-di-q05", type: "qcm", prompt: "Quel mot vient après « lune » dans l'ordre alphabétique ?", options: ["mer", "lit", "loup", "lapin"], correctIndex: 0 },
        { id: "fr-di-q06", type: "qcm", prompt: "Dans une définition de dictionnaire, l'abréviation « n.m. » signifie :", options: ["nom masculin", "nom multiple", "nouveau mot", "nom mauvais"], correctIndex: 0 },
        { id: "fr-di-q07", type: "true-false", prompt: "« pomme » est classé avant « poire » dans l'ordre alphabétique.", correct: false, explanation: "« poire » vient avant « pomme » car le « i » précède le « m »." },
        { id: "fr-di-q08", type: "qcm", prompt: "Que signifie l'abréviation « v. » dans un dictionnaire ?", options: ["verbe", "ville", "vrai", "voyelle"], correctIndex: 0 },
      ],
    },
    {
      id: "comprehension",
      title: "Compréhension de texte",
      description: "Comprendre de courts textes et répondre à des questions",
      icon: "🔍",
      exercises: [
        { id: "fr-co-q01", type: "qcm", prompt: "« Léo se réveille à 7h, prend son petit-déjeuner puis part à l'école. » À quelle heure Léo se réveille-t-il ?", options: ["7h", "8h", "6h", "9h"], correctIndex: 0 },
        { id: "fr-co-q02", type: "qcm", prompt: "« Le chat de Sara s'appelle Mimi. Il est noir et blanc et adore dormir au soleil. » Quelle couleur est le chat ?", options: ["noir et blanc", "gris", "roux", "blanc seulement"], correctIndex: 0 },
        { id: "fr-co-q03", type: "true-false", prompt: "« Il pleuvait, alors Tom a pris son parapluie avant de sortir. » Tom est sorti sans rien.", correct: false, explanation: "Tom a pris son parapluie avant de sortir." },
        { id: "fr-co-q04", type: "qcm", prompt: "« Après l'école, Emma fait ses devoirs puis joue avec son frère. » Que fait Emma en premier après l'école ?", options: ["ses devoirs", "elle joue", "elle dort", "elle mange"], correctIndex: 0 },
        { id: "fr-co-q05", type: "fill-blank", prompt: "« Le marchand vend des pommes, des poires et des bananes. » Combien de fruits différents le marchand vend-il ? ___", acceptedAnswers: ["3"] },
        { id: "fr-co-q06", type: "qcm", prompt: "« Hugo a oublié son cartable, il a dû retourner à la maison. » Pourquoi Hugo retourne-t-il à la maison ?", options: ["il a oublié son cartable", "il est malade", "il a faim", "il veut jouer"], correctIndex: 0 },
        { id: "fr-co-q07", type: "true-false", prompt: "« La maîtresse a annoncé une sortie au musée vendredi. » La sortie a lieu un lundi.", correct: false, explanation: "La sortie a lieu vendredi, pas lundi." },
        { id: "fr-co-q08", type: "qcm", prompt: "« Les abeilles butinent les fleurs pour fabriquer du miel. » Que fabriquent les abeilles ?", options: ["du miel", "du sucre", "de la cire seulement", "du pollen pur"], correctIndex: 0 },
      ],
    },
    {
      id: "pronoms",
      title: "Les pronoms",
      description: "Reconnaître et utiliser les pronoms personnels",
      icon: "👉",
      exercises: [
        { id: "fr-pn-q01", type: "qcm", prompt: "Dans « Il mange une pomme », « il » est :", options: ["un pronom", "un nom", "un verbe", "un adjectif"], correctIndex: 0 },
        { id: "fr-pn-q02", type: "qcm", prompt: "Quel pronom remplace « Marie » dans « Marie joue dans le jardin » ?", options: ["Elle", "Il", "Ils", "Elles"], correctIndex: 0 },
        { id: "fr-pn-q03", type: "fill-blank", prompt: "Dans « Paul et Tom jouent », on peut remplacer « Paul et Tom » par le pronom ___", acceptedAnswers: ["ils"] },
        { id: "fr-pn-q04", type: "true-false", prompt: "« Je », « tu » et « il » sont des pronoms personnels.", correct: true },
        { id: "fr-pn-q05", type: "qcm", prompt: "Dans « Le chat mange sa pâtée, il l'adore », que remplace « l' » ?", options: ["sa pâtée", "le chat", "il", "mange"], correctIndex: 0 },
        { id: "fr-pn-q06", type: "qcm", prompt: "Quel est le pronom personnel de la 1ère personne du pluriel ?", options: ["nous", "vous", "ils", "elle"], correctIndex: 0 },
        { id: "fr-pn-q07", type: "true-false", prompt: "« Celui-ci » est un pronom démonstratif.", correct: true },
        { id: "fr-pn-q08", type: "fill-blank", prompt: "Remplace « les enfants » par un pronom : ___ jouent dans la cour.", acceptedAnswers: ["ils"] },
        { id: "fr-pn-q09", type: "qcm", prompt: "Dans « Donne-moi ce livre », « moi » est :", options: ["un pronom", "un nom", "un adjectif", "un déterminant"], correctIndex: 0 },
      ],
    },
    {
      id: "complements-verbe",
      title: "Les compléments du verbe",
      description: "Identifier le COD et le COI dans une phrase",
      icon: "🎯",
      exercises: [
        { id: "fr-cv-q01", type: "qcm", prompt: "Dans « Il mange une pomme », « une pomme » est :", options: ["un COD", "un sujet", "un COI", "un adjectif"], correctIndex: 0 },
        { id: "fr-cv-q02", type: "qcm", prompt: "Le COD répond à la question :", options: ["quoi ? ou qui ? (sans préposition)", "où ?", "quand ?", "comment ?"], correctIndex: 0 },
        { id: "fr-cv-q03", type: "fill-blank", prompt: "Dans « Elle pense à son ami », « à son ami » est un COI car il est introduit par la préposition ___", acceptedAnswers: ["à"] },
        { id: "fr-cv-q04", type: "qcm", prompt: "Dans « Tom offre un cadeau à sa sœur », quel est le COD ?", options: ["un cadeau", "à sa sœur", "Tom", "offre"], correctIndex: 0 },
        { id: "fr-cv-q05", type: "qcm", prompt: "Dans la même phrase, quel est le COI ?", options: ["à sa sœur", "un cadeau", "Tom", "offre"], correctIndex: 0 },
        { id: "fr-cv-q06", type: "true-false", prompt: "Le COI est toujours introduit par une préposition (à, de...).", correct: true },
        { id: "fr-cv-q07", type: "qcm", prompt: "Dans « Léa regarde la télévision », « la télévision » est :", options: ["un COD", "un COI", "un sujet", "un attribut"], correctIndex: 0 },
        { id: "fr-cv-q08", type: "fill-blank", prompt: "Le COD et le COI complètent le ___", acceptedAnswers: ["verbe"] },
        { id: "fr-cv-q09", type: "true-false", prompt: "« Il dort. » contient un COD.", correct: false, explanation: "« Dort » n'a pas de complément : il n'y a pas de COD dans cette phrase." },
      ],
    },
  ],
};
