import type { Subject } from "../types";

export const francaisCm1: Subject = {
  id: "francais-cm1",
  name: "Français",
  icon: "📖",
  colorFrom: "from-rose-500",
  colorTo: "to-orange-500",
  chapters: [
    {
      id: "nature-des-mots",
      title: "Nature des mots",
      description: "Noms, verbes, adjectifs et déterminants",
      icon: "🔤",
      exercises: [
        { id: "fr-nm-q01", type: "qcm", prompt: "Dans « le petit chat dort », quel mot est un adjectif ?", options: ["petit", "chat", "dort", "le"], correctIndex: 0 },
        { id: "fr-nm-q02", type: "qcm", prompt: "Quel mot est un verbe dans « elle chante une chanson » ?", options: ["chante", "elle", "une", "chanson"], correctIndex: 0 },
        { id: "fr-nm-q03", type: "true-false", prompt: "« table » est un nom commun.", correct: true },
        { id: "fr-nm-q04", type: "qcm", prompt: "Quel est le déterminant dans « les enfants jouent » ?", options: ["les", "enfants", "jouent", "aucun"], correctIndex: 0 },
        { id: "fr-nm-q05", type: "fill-blank", prompt: "Dans « Paris est une grande ville », le mot « Paris » est un nom ___ (commun ou propre).", acceptedAnswers: ["propre"] },
        { id: "fr-nm-q06", type: "qcm", prompt: "Quel mot est un adjectif dans « une jolie maison bleue » ?", options: ["jolie", "maison", "une", "et"], correctIndex: 0 },
        { id: "fr-nm-q07", type: "true-false", prompt: "Un verbe peut se conjuguer.", correct: true },
        { id: "fr-nm-q08", type: "qcm", prompt: "Quelle est la nature du mot souligné : « il COURT vite » ?", options: ["un verbe", "un nom", "un adjectif", "un déterminant"], correctIndex: 0 },
        { id: "fr-nm-q09", type: "qcm", prompt: "Lequel de ces mots est un pronom ?", options: ["elle", "rapide", "maison", "chanter"], correctIndex: 0 },
        { id: "fr-nm-q10", type: "true-false", prompt: "Un adjectif qualificatif donne une précision sur un nom.", correct: true },
      ],
    },
    {
      id: "conjugaison-present",
      title: "Conjugaison : le présent",
      description: "Conjuguer au présent les verbes courants",
      icon: "📝",
      exercises: [
        { id: "fr-cp-q01", type: "qcm", prompt: "Conjugue « chanter » au présent avec « je » :", options: ["je chante", "je chantes", "je chantons", "je chantai"], correctIndex: 0 },
        { id: "fr-cp-q02", type: "qcm", prompt: "Conjugue « avoir » au présent avec « nous » :", options: ["nous avons", "nous avez", "nous ai", "nous a"], correctIndex: 0 },
        { id: "fr-cp-q03", type: "fill-blank", prompt: "Conjugue « être » au présent avec « tu » : tu ___", acceptedAnswers: ["es"] },
        { id: "fr-cp-q04", type: "qcm", prompt: "Conjugue « aller » au présent avec « ils » :", options: ["ils vont", "ils allent", "ils va", "ils allons"], correctIndex: 0 },
        { id: "fr-cp-q05", type: "true-false", prompt: "Au présent, avec « il/elle », les verbes en -er se terminent par -e.", correct: true },
        { id: "fr-cp-q06", type: "qcm", prompt: "Conjugue « finir » au présent avec « vous » :", options: ["vous finissez", "vous finez", "vous finissont", "vous finis"], correctIndex: 0 },
        { id: "fr-cp-q07", type: "fill-blank", prompt: "Conjugue « faire » au présent avec « je » : je ___", acceptedAnswers: ["fais"] },
        { id: "fr-cp-q08", type: "qcm", prompt: "Quelle phrase est correctement conjuguée au présent ?", options: ["Elle joue dans le jardin.", "Elle jouent dans le jardin.", "Elle jouez dans le jardin.", "Elle jouons dans le jardin."], correctIndex: 0 },
        { id: "fr-cp-q09", type: "true-false", prompt: "« Je peux » est la conjugaison correcte du verbe « pouvoir » au présent avec « je ».", correct: true },
        { id: "fr-cp-q10", type: "qcm", prompt: "Conjugue « venir » au présent avec « tu » :", options: ["tu viens", "tu vient", "tu venez", "tu venons"], correctIndex: 0 },
      ],
    },
    {
      id: "conjugaison-futur-imparfait",
      title: "Conjugaison : futur et imparfait",
      description: "Conjuguer les verbes courants à ces deux temps",
      icon: "🕰️",
      exercises: [
        { id: "fr-fi-q01", type: "qcm", prompt: "Conjugue « jouer » au futur avec « je » :", options: ["je jouerai", "je jouais", "je joue", "je jouerais"], correctIndex: 0 },
        { id: "fr-fi-q02", type: "qcm", prompt: "Conjugue « chanter » à l'imparfait avec « il » :", options: ["il chantait", "il chanta", "il chantera", "il chante"], correctIndex: 0 },
        { id: "fr-fi-q03", type: "fill-blank", prompt: "Conjugue « avoir » au futur avec « nous » : nous ___", acceptedAnswers: ["aurons"] },
        { id: "fr-fi-q04", type: "true-false", prompt: "L'imparfait sert souvent à décrire ou à raconter une habitude dans le passé.", correct: true },
        { id: "fr-fi-q05", type: "qcm", prompt: "Conjugue « être » à l'imparfait avec « tu » :", options: ["tu étais", "tu seras", "tu es", "tu fus"], correctIndex: 0 },
        { id: "fr-fi-q06", type: "qcm", prompt: "Conjugue « manger » au futur avec « ils » :", options: ["ils mangeront", "ils mangeaient", "ils mangent", "ils mangèrent"], correctIndex: 0 },
        { id: "fr-fi-q07", type: "fill-blank", prompt: "Conjugue « aller » à l'imparfait avec « je » : j'___", acceptedAnswers: ["allais"] },
        { id: "fr-fi-q08", type: "true-false", prompt: "Au futur, tous les verbes du 1er groupe se terminent par -erai, -eras, -era... avec « je, tu, il »", correct: true },
        { id: "fr-fi-q09", type: "qcm", prompt: "Quelle phrase est au futur ?", options: ["Demain, nous partirons en vacances.", "Hier, nous partions en vacances.", "Nous partons en vacances.", "Nous étions en vacances."], correctIndex: 0 },
        { id: "fr-fi-q10", type: "qcm", prompt: "Conjugue « finir » au futur avec « elle » :", options: ["elle finira", "elle finissait", "elle finit", "elle finirait"], correctIndex: 0 },
      ],
    },
    {
      id: "accords",
      title: "Accords",
      description: "Pluriels des noms et accord des adjectifs",
      icon: "🔗",
      exercises: [
        { id: "fr-ac-q01", type: "qcm", prompt: "Quel est le pluriel de « un cheval » ?", options: ["des chevaux", "des chevals", "des chevaus", "des cheval"], correctIndex: 0 },
        { id: "fr-ac-q02", type: "qcm", prompt: "Quel est le pluriel de « un chou » ?", options: ["des choux", "des chous", "des choues", "des chou"], correctIndex: 0 },
        { id: "fr-ac-q03", type: "fill-blank", prompt: "Accorde : « une jolie fleur ___ » (fleur au pluriel : des jolies fleur___)", acceptedAnswers: ["s"] },
        { id: "fr-ac-q04", type: "true-false", prompt: "Le verbe s'accorde toujours avec son sujet.", correct: true },
        { id: "fr-ac-q05", type: "qcm", prompt: "Choisis l'accord correct : « Les enfants ___ contents. »", options: ["sont", "est", "es", "soient"], correctIndex: 0 },
        { id: "fr-ac-q06", type: "qcm", prompt: "Quel est le féminin de « un grand chat » ?", options: ["une grande chatte", "un grande chat", "une grand chatte", "une grande chat"], correctIndex: 0 },
        { id: "fr-ac-q07", type: "fill-blank", prompt: "« Les chats ___ noirs. » (verbe être au présent)", acceptedAnswers: ["sont"] },
        { id: "fr-ac-q08", type: "true-false", prompt: "« Des beaux jardins » est correctement accordé.", correct: true },
        { id: "fr-ac-q09", type: "qcm", prompt: "Quel est le pluriel de « un journal » ?", options: ["des journaux", "des journals", "des journales", "des journau"], correctIndex: 0 },
        { id: "fr-ac-q10", type: "qcm", prompt: "Accorde : « Marie et Léa ___ arrivées. »", options: ["sont", "est", "es", "a"], correctIndex: 0 },
      ],
    },
    {
      id: "homophones",
      title: "Homophones grammaticaux",
      description: "a/à, et/est, son/sont, ce/se, ou/où",
      icon: "🤔",
      exercises: [
        { id: "fr-ho-q01", type: "qcm", prompt: "Complète : « Il ___ allé au parc. »", options: ["est", "et", "es", "ai"], correctIndex: 0 },
        { id: "fr-ho-q02", type: "qcm", prompt: "Complète : « Léa ___ Tom jouent ensemble. »", options: ["et", "est", "es", "ai"], correctIndex: 0 },
        { id: "fr-ho-q03", type: "fill-blank", prompt: "Complète : « Il a perdu ___ ballon. » (a ou à ?)", acceptedAnswers: ["a"] },
        { id: "fr-ho-q04", type: "qcm", prompt: "Complète : « Je vais ___ l'école. »", options: ["à", "a", "as", "ah"], correctIndex: 0 },
        { id: "fr-ho-q05", type: "true-false", prompt: "« Son chien et sa chatte sont dans le jardin » utilise correctement « son » et « sont ».", correct: true },
        { id: "fr-ho-q06", type: "qcm", prompt: "Complète : « Les enfants ___ dans la cour. »", options: ["sont", "son", "s'ont", "s'on"], correctIndex: 0 },
        { id: "fr-ho-q07", type: "qcm", prompt: "Complète : « Le chat lave ___ pelage. »", options: ["son", "sont", "s'on", "sons"], correctIndex: 0 },
        { id: "fr-ho-q08", type: "fill-blank", prompt: "Complète : « ___ chien aboie fort. » (ce ou se ?)", acceptedAnswers: ["ce"] },
        { id: "fr-ho-q09", type: "qcm", prompt: "Complète : « Il ___ lave les mains. »", options: ["se", "ce", "ceux", "sai"], correctIndex: 0 },
        { id: "fr-ho-q10", type: "qcm", prompt: "Complète : « Tu préfères les pommes ___ les poires ? »", options: ["ou", "où", "houx", "août"], correctIndex: 0 },
        { id: "fr-ho-q11", type: "qcm", prompt: "Complète : « ___ est la maison de Théo ? »", options: ["Où", "Ou", "Houx", "Août"], correctIndex: 0 },
      ],
    },
    {
      id: "vocabulaire",
      title: "Vocabulaire",
      description: "Synonymes, antonymes et familles de mots",
      icon: "📚",
      exercises: [
        { id: "fr-vo-q01", type: "qcm", prompt: "Quel mot est un synonyme de « content » ?", options: ["heureux", "triste", "fatigué", "grand"], correctIndex: 0 },
        { id: "fr-vo-q02", type: "qcm", prompt: "Quel mot est l'antonyme (contraire) de « grand » ?", options: ["petit", "joli", "rapide", "lourd"], correctIndex: 0 },
        { id: "fr-vo-q03", type: "fill-blank", prompt: "Le contraire de « chaud » est ___.", acceptedAnswers: ["froid"] },
        { id: "fr-vo-q04", type: "qcm", prompt: "Quel mot appartient à la famille de « terre » ?", options: ["atterrir", "terrible", "terrasse vide", "terne"], correctIndex: 0 },
        { id: "fr-vo-q05", type: "true-false", prompt: "« rapide » et « lent » sont des antonymes.", correct: true },
        { id: "fr-vo-q06", type: "qcm", prompt: "Quel mot est un synonyme de « commencer » ?", options: ["débuter", "finir", "arrêter", "dormir"], correctIndex: 0 },
        { id: "fr-vo-q07", type: "fill-blank", prompt: "Le synonyme de « rapide » est ___.", acceptedAnswers: ["vite", "véloce"] },
        { id: "fr-vo-q08", type: "qcm", prompt: "Quel mot fait partie de la famille de « chant » ?", options: ["chanteur", "champ", "chance", "chaud"], correctIndex: 0 },
        { id: "fr-vo-q09", type: "true-false", prompt: "« beau » et « joli » peuvent être des synonymes.", correct: true },
        { id: "fr-vo-q10", type: "qcm", prompt: "Quel est l'antonyme de « monter » ?", options: ["descendre", "sauter", "courir", "voler"], correctIndex: 0 },
      ],
    },
    {
      id: "la-phrase",
      title: "La phrase et la ponctuation",
      description: "Types de phrases et ponctuation",
      icon: "❓",
      exercises: [
        { id: "fr-ph-q01", type: "qcm", prompt: "« Quel âge as-tu ? » est une phrase :", options: ["interrogative", "déclarative", "exclamative", "impérative"], correctIndex: 0 },
        { id: "fr-ph-q02", type: "qcm", prompt: "« Quelle belle journée ! » est une phrase :", options: ["exclamative", "interrogative", "déclarative", "négative"], correctIndex: 0 },
        { id: "fr-ph-q03", type: "true-false", prompt: "Une phrase déclarative se termine par un point.", correct: true },
        { id: "fr-ph-q04", type: "fill-blank", prompt: "Une phrase interrogative se termine par un point ___.", acceptedAnswers: ["d'interrogation"] },
        { id: "fr-ph-q05", type: "qcm", prompt: "« Range ta chambre ! » est une phrase :", options: ["impérative", "interrogative", "déclarative", "exclamative seulement"], correctIndex: 0 },
        { id: "fr-ph-q06", type: "qcm", prompt: "Toute phrase commence par :", options: ["une majuscule", "une minuscule", "un chiffre", "un tiret"], correctIndex: 0 },
        { id: "fr-ph-q07", type: "true-false", prompt: "« Le chat dort. » est une phrase négative.", correct: false, explanation: "C'est une phrase affirmative. La forme négative serait « Le chat ne dort pas. »" },
        { id: "fr-ph-q08", type: "qcm", prompt: "Quelle est la forme négative de « Il aime les épinards. » ?", options: ["Il n'aime pas les épinards.", "Il aime pas les épinards.", "Il aime les épinards pas.", "Il n'aime les épinards."], correctIndex: 0 },
        { id: "fr-ph-q09", type: "qcm", prompt: "Dans une phrase, le sujet fait l'action. Quel est le sujet de « Le chien mange sa pâtée. » ?", options: ["Le chien", "mange", "sa pâtée", "aucun"], correctIndex: 0 },
      ],
    },
  ],
};
