import type { Subject } from "../types";

export const mathsCm1: Subject = {
  id: "maths-cm1",
  name: "Maths",
  icon: "🔢",
  colorFrom: "from-sky-500",
  colorTo: "to-blue-600",
  chapters: [
    {
      id: "grands-nombres",
      title: "Les grands nombres",
      description: "Lire, écrire et comparer les nombres jusqu'au million",
      icon: "🔢",
      exercises: [
        { id: "maths-gn-q01", type: "qcm", prompt: "Comment s'écrit en chiffres « douze mille trois cent quarante » ?", options: ["12 340", "1 234", "123 400", "12 304"], correctIndex: 0 },
        { id: "maths-gn-q02", type: "qcm", prompt: "Dans le nombre 45 678, quel chiffre représente les milliers ?", options: ["5", "4", "6", "7"], correctIndex: 0 },
        { id: "maths-gn-q03", type: "true-false", prompt: "1000 unités de mille font un million.", correct: false, explanation: "Il faut 1000 milliers pour faire un million (1 000 000)." },
        { id: "maths-gn-q04", type: "qcm", prompt: "Range dans l'ordre croissant : 4502 ; 4250 ; 4520 ; 4025.", options: ["4025 < 4250 < 4502 < 4520", "4520 < 4502 < 4250 < 4025", "4025 < 4502 < 4250 < 4520", "4250 < 4025 < 4502 < 4520"], correctIndex: 0 },
        { id: "maths-gn-q05", type: "fill-blank", prompt: "Le nombre juste avant 100 000 est ___.", acceptedAnswers: ["99999", "99 999"] },
        { id: "maths-gn-q06", type: "qcm", prompt: "Quel est le plus grand nombre ?", options: ["98 765", "9 8765", "9 876", "8 976"], correctIndex: 0 },
        { id: "maths-gn-q07", type: "true-false", prompt: "Dans 305 209, il y a 3 centaines de mille.", correct: true },
        { id: "maths-gn-q08", type: "qcm", prompt: "Comment écrit-on 7 050 en lettres ?", options: ["sept mille cinquante", "sept cent cinquante", "soixante-dix-cinq", "sept mille cinq cents"], correctIndex: 0 },
        { id: "maths-gn-q09", type: "fill-blank", prompt: "Pour décomposer 4 632, on écrit 4000 + 600 + 30 + ___.", acceptedAnswers: ["2"] },
        { id: "maths-gn-q10", type: "qcm", prompt: "Quel nombre est compris entre 12 000 et 12 100 ?", options: ["12 045", "11 999", "12 999", "13 000"], correctIndex: 0 },
        { id: "maths-gn-q11", type: "true-false", prompt: "999 999 + 1 = 1 000 000", correct: true },
      ],
    },
    {
      id: "addition-soustraction",
      title: "Addition et soustraction",
      description: "Calculer en colonnes avec ou sans retenue",
      icon: "➕",
      exercises: [
        { id: "maths-as-q01", type: "qcm", prompt: "245 + 137 = ?", options: ["382", "372", "382", "292"], correctIndex: 0 },
        { id: "maths-as-q02", type: "qcm", prompt: "1 250 + 875 = ?", options: ["2 125", "2 025", "2 225", "1 925"], correctIndex: 0 },
        { id: "maths-as-q03", type: "fill-blank", prompt: "603 − 248 = ___", acceptedAnswers: ["355"] },
        { id: "maths-as-q04", type: "qcm", prompt: "1 000 − 376 = ?", options: ["624", "634", "734", "626"], correctIndex: 0 },
        { id: "maths-as-q05", type: "true-false", prompt: "Pour soustraire, on commence toujours par les unités, à droite.", correct: true },
        { id: "maths-as-q06", type: "qcm", prompt: "Quelle est la somme de 4 528 et 1 372 ?", options: ["5 900", "5 800", "6 000", "5 890"], correctIndex: 0 },
        { id: "maths-as-q07", type: "fill-blank", prompt: "82 + 19 = ___", acceptedAnswers: ["101"] },
        { id: "maths-as-q08", type: "qcm", prompt: "Marc a 350 billes, il en gagne 128. Combien en a-t-il ?", options: ["478", "468", "488", "522"], correctIndex: 0 },
        { id: "maths-as-q09", type: "true-false", prompt: "9 − 9 = 0", correct: true },
        { id: "maths-as-q10", type: "qcm", prompt: "Une classe de 27 élèves perd 5 élèves partis en voyage. Combien reste-t-il d'élèves ?", options: ["22", "32", "21", "23"], correctIndex: 0 },
        { id: "maths-as-q11", type: "qcm", prompt: "2 304 − 1 158 = ?", options: ["1 146", "1 156", "1 046", "1 246"], correctIndex: 0 },
      ],
    },
    {
      id: "multiplication",
      title: "Multiplication",
      description: "Tables et multiplication posée",
      icon: "✖️",
      exercises: [
        { id: "maths-mu-q01", type: "qcm", prompt: "7 × 8 = ?", options: ["56", "54", "64", "48"], correctIndex: 0 },
        { id: "maths-mu-q02", type: "qcm", prompt: "9 × 6 = ?", options: ["54", "56", "45", "63"], correctIndex: 0 },
        { id: "maths-mu-q03", type: "fill-blank", prompt: "12 × 5 = ___", acceptedAnswers: ["60"] },
        { id: "maths-mu-q04", type: "qcm", prompt: "234 × 3 = ?", options: ["702", "692", "712", "642"], correctIndex: 0 },
        { id: "maths-mu-q05", type: "true-false", prompt: "Multiplier un nombre par 10 revient à lui ajouter un zéro à la fin.", correct: true },
        { id: "maths-mu-q06", type: "qcm", prompt: "8 × 0 = ?", options: ["0", "8", "1", "80"], correctIndex: 0 },
        { id: "maths-mu-q07", type: "qcm", prompt: "45 × 10 = ?", options: ["450", "45", "4500", "405"], correctIndex: 0 },
        { id: "maths-mu-q08", type: "fill-blank", prompt: "6 × 7 = ___", acceptedAnswers: ["42"] },
        { id: "maths-mu-q09", type: "true-false", prompt: "4 × 25 = 100", correct: true },
        { id: "maths-mu-q10", type: "qcm", prompt: "Un paquet contient 8 gâteaux. Combien de gâteaux dans 6 paquets ?", options: ["48", "42", "54", "56"], correctIndex: 0 },
        { id: "maths-mu-q11", type: "qcm", prompt: "125 × 4 = ?", options: ["500", "450", "520", "480"], correctIndex: 0 },
      ],
    },
    {
      id: "division",
      title: "Division",
      description: "Sens de la division et division posée simple",
      icon: "➗",
      exercises: [
        { id: "maths-di-q01", type: "qcm", prompt: "36 ÷ 6 = ?", options: ["6", "5", "7", "8"], correctIndex: 0 },
        { id: "maths-di-q02", type: "qcm", prompt: "48 ÷ 8 = ?", options: ["6", "8", "7", "5"], correctIndex: 0 },
        { id: "maths-di-q03", type: "fill-blank", prompt: "72 ÷ 9 = ___", acceptedAnswers: ["8"] },
        { id: "maths-di-q04", type: "true-false", prompt: "Dans une division, le résultat s'appelle le quotient.", correct: true },
        { id: "maths-di-q05", type: "qcm", prompt: "On partage 20 bonbons entre 4 enfants. Combien chacun en a-t-il ?", options: ["5", "4", "6", "8"], correctIndex: 0 },
        { id: "maths-di-q06", type: "qcm", prompt: "63 ÷ 7 = ?", options: ["9", "8", "7", "10"], correctIndex: 0 },
        { id: "maths-di-q07", type: "fill-blank", prompt: "Dans 17 ÷ 5, le quotient est 3 et le reste est ___.", acceptedAnswers: ["2"] },
        { id: "maths-di-q08", type: "true-false", prompt: "Le reste d'une division doit toujours être plus petit que le diviseur.", correct: true },
        { id: "maths-di-q09", type: "qcm", prompt: "84 ÷ 4 = ?", options: ["21", "20", "22", "24"], correctIndex: 0 },
        { id: "maths-di-q10", type: "qcm", prompt: "Une boîte contient 6 œufs. Combien de boîtes pour ranger 54 œufs ?", options: ["9", "8", "7", "6"], correctIndex: 0 },
      ],
    },
    {
      id: "fractions",
      title: "Fractions simples",
      description: "Comprendre et représenter une fraction",
      icon: "🍕",
      exercises: [
        { id: "maths-fr-q01", type: "qcm", prompt: "Une pizza coupée en 4 parts égales : si je mange 1 part, j'ai mangé :", options: ["1/4 de la pizza", "1/2 de la pizza", "1/3 de la pizza", "4 pizzas"], correctIndex: 0 },
        { id: "maths-fr-q02", type: "true-false", prompt: "Dans la fraction 3/5, 5 est le dénominateur.", correct: true },
        { id: "maths-fr-q03", type: "qcm", prompt: "Quelle fraction représente la moitié d'un gâteau ?", options: ["1/2", "1/4", "2/2", "1/3"], correctIndex: 0 },
        { id: "maths-fr-q04", type: "fill-blank", prompt: "Dans 2/3, le numérateur est ___.", acceptedAnswers: ["2"] },
        { id: "maths-fr-q05", type: "qcm", prompt: "3/4 + 1/4 = ?", options: ["1", "4/4", "2/4", "3/8"], correctIndex: 0, explanation: "3/4 + 1/4 = 4/4, c'est-à-dire 1 entier." },
        { id: "maths-fr-q06", type: "true-false", prompt: "2/2 représente un tout entier.", correct: true },
        { id: "maths-fr-q07", type: "qcm", prompt: "Une bande est partagée en 8 parts égales, j'en colorie 3. Quelle fraction est coloriée ?", options: ["3/8", "8/3", "3/5", "5/8"], correctIndex: 0 },
        { id: "maths-fr-q08", type: "qcm", prompt: "Quelle fraction est égale à 1 (un tout) ?", options: ["5/5", "5/1", "1/5", "0/5"], correctIndex: 0 },
        { id: "maths-fr-q09", type: "fill-blank", prompt: "1/4 + 1/4 + 1/4 = ___ (sous forme de fraction)", acceptedAnswers: ["3/4"] },
      ],
    },
    {
      id: "mesures",
      title: "Mesures",
      description: "Longueurs, masses et contenances",
      icon: "📏",
      exercises: [
        { id: "maths-me-q01", type: "qcm", prompt: "Combien de centimètres dans 1 mètre ?", options: ["100", "10", "1000", "50"], correctIndex: 0 },
        { id: "maths-me-q02", type: "qcm", prompt: "Combien de grammes dans 1 kilogramme ?", options: ["1000", "100", "10", "10000"], correctIndex: 0 },
        { id: "maths-me-q03", type: "fill-blank", prompt: "1 litre = ___ centilitres", acceptedAnswers: ["100"] },
        { id: "maths-me-q04", type: "true-false", prompt: "1 km = 1000 m", correct: true },
        { id: "maths-me-q05", type: "qcm", prompt: "Quel objet pèse environ 1 kg ?", options: ["Un paquet de farine", "Une fourmi", "Un camion", "Une plume"], correctIndex: 0 },
        { id: "maths-me-q06", type: "qcm", prompt: "Combien de millimètres dans 1 centimètre ?", options: ["10", "100", "1000", "1"], correctIndex: 0 },
        { id: "maths-me-q07", type: "fill-blank", prompt: "3 m = ___ cm", acceptedAnswers: ["300"] },
        { id: "maths-me-q08", type: "true-false", prompt: "Pour peser un objet, on utilise une balance.", correct: true },
        { id: "maths-me-q09", type: "qcm", prompt: "2 kg 500 g, c'est aussi :", options: ["2500 g", "250 g", "25 g", "20500 g"], correctIndex: 0 },
        { id: "maths-me-q10", type: "qcm", prompt: "Quelle unité utilise-t-on pour mesurer la quantité d'eau dans une bouteille ?", options: ["Le litre", "Le mètre", "Le gramme", "Le degré"], correctIndex: 0 },
      ],
    },
    {
      id: "geometrie",
      title: "Géométrie",
      description: "Figures planes, droites et périmètre",
      icon: "📐",
      exercises: [
        { id: "maths-ge-q01", type: "qcm", prompt: "Combien de côtés a un carré ?", options: ["4", "3", "5", "6"], correctIndex: 0 },
        { id: "maths-ge-q02", type: "true-false", prompt: "Un carré a quatre côtés de même longueur.", correct: true },
        { id: "maths-ge-q03", type: "qcm", prompt: "Quel est le périmètre d'un carré de 5 cm de côté ?", options: ["20 cm", "25 cm", "10 cm", "15 cm"], correctIndex: 0 },
        { id: "maths-ge-q04", type: "fill-blank", prompt: "Un rectangle de longueur 6 cm et largeur 3 cm a un périmètre de ___ cm.", acceptedAnswers: ["18"] },
        { id: "maths-ge-q05", type: "qcm", prompt: "Comment s'appelle une figure à 3 côtés ?", options: ["Un triangle", "Un carré", "Un pentagone", "Un cercle"], correctIndex: 0 },
        { id: "maths-ge-q06", type: "true-false", prompt: "Deux droites parallèles ne se croisent jamais.", correct: true },
        { id: "maths-ge-q07", type: "qcm", prompt: "Comment s'appelle l'angle d'un carré ?", options: ["Un angle droit", "Un angle plat", "Un angle aigu", "Un angle rond"], correctIndex: 0 },
        { id: "maths-ge-q08", type: "qcm", prompt: "Combien de côtés a un pentagone ?", options: ["5", "4", "6", "3"], correctIndex: 0 },
        { id: "maths-ge-q09", type: "true-false", prompt: "Un cercle a des côtés droits.", correct: false, explanation: "Un cercle est une courbe fermée, il n'a pas de côtés droits." },
        { id: "maths-ge-q10", type: "fill-blank", prompt: "Un triangle équilatéral a ses trois côtés de longueur ___.", acceptedAnswers: ["égale", "identique"] },
      ],
    },
    {
      id: "le-temps",
      title: "Le temps",
      description: "Lire l'heure et calculer des durées",
      icon: "⏰",
      exercises: [
        { id: "maths-te-q01", type: "qcm", prompt: "Combien d'heures dans une journée ?", options: ["24", "12", "60", "7"], correctIndex: 0 },
        { id: "maths-te-q02", type: "qcm", prompt: "Combien de minutes dans une heure ?", options: ["60", "100", "30", "24"], correctIndex: 0 },
        { id: "maths-te-q03", type: "fill-blank", prompt: "Une semaine compte ___ jours.", acceptedAnswers: ["7"] },
        { id: "maths-te-q04", type: "true-false", prompt: "Il est 14h, c'est la même heure que 2h de l'après-midi.", correct: true },
        { id: "maths-te-q05", type: "qcm", prompt: "Un film commence à 15h30 et dure 1h30. À quelle heure se termine-t-il ?", options: ["17h00", "16h30", "16h00", "17h30"], correctIndex: 0 },
        { id: "maths-te-q06", type: "qcm", prompt: "Combien de mois y a-t-il dans une année ?", options: ["12", "10", "52", "365"], correctIndex: 0 },
        { id: "maths-te-q07", type: "fill-blank", prompt: "Une demi-heure correspond à ___ minutes.", acceptedAnswers: ["30"] },
        { id: "maths-te-q08", type: "true-false", prompt: "Une année bissextile compte 366 jours.", correct: true },
        { id: "maths-te-q09", type: "qcm", prompt: "Léa part à l'école à 8h15 et le trajet dure 20 minutes. À quelle heure arrive-t-elle ?", options: ["8h35", "8h45", "8h30", "9h00"], correctIndex: 0 },
      ],
    },
  ],
};
